name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Ensure Mocha is executable
        run: chmod +x ./node_modules/.bin/mocha

      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npm test

      - name: Run failure tests
        run: npm run test:failures || exit 1  # Exit with code 1 if failure tests fail

      - name: Build Docker image
        run: |
          docker build -t hani9/piplinehani:latest .
          docker images  # Optional: display Docker images for verification

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push hani9/piplinehani:latest
